dist: xenial
language: rust
rust: stable
cache: cargo
script:
    - cargo build --verbose --release
    - cargo test --verbose --release
before_deploy:
    - cd target/release
    - tar cjvf ../../geoip-rs-$TRAVIS_TAG-linux-amd64.tar.bz2 geoip-rs
    - cd $TRAVIS_BUILD_DIR
deploy:
    provider: releases
    api_key: $GH_TOKEN
    file_glob: true
    file: geoip-rs*.tar.bz2
    skip_cleanup: true
    on:
        tags: true
